[window]
decorations = "None"
padding = { x = 2, y = 2 }
dynamic_padding = true
opacity=0.92
blur=true
[mouse]
hide_when_typing = true
[font]
normal = { family = "Hasklug Nerd Font Mono", style = "Regular" }
[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
]

# Colors (Everforest Light)

# Default colors
[colors.primary]
background = '#fdf6e3'
foreground = '#5c6a72'

# Normal colors
[colors.normal]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#e0dcc7'

# Bright Colors
[colors.bright]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#e0dcc7'
